config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/teachers')

  resources :subjects, only: [:index, :show]

  resources :students, only: [:new, :create, :edit, :update]

  resources :teachers, only: [:new, :create, :edit, :update, :index, :show] do
    resources :lessons, only: [:new, :create]
  end

  resources :lessons, only: [:show, :destroy]

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :availability_ranges, only: [:new, :create, :show, :edit, :update, :destroy]



end

app/models/availability_range.rb
class AvailabilityRange < ApplicationRecord
  belongs_to :teacher
  validates_uniqueness_of :weekday, scope: :teacher_id
  validate :start_time_before_end_time

  def start_time_before_end_time
    unless self.start_time < self.end_time
      errors.add(:end_time, "Your end time must be later than your start time")
    end
  end

  def start_time_to_12h
    t = self.start_time
    time_12h(t)
  end

  def end_time_to_12h
    t = self.end_time
    time_12h(t)
  end

  def sum_of_hours
    self.end_time - self.start_time
  end

  def time_12h(t)
    case t
    when 0
      "12 AM"
    when 1..11
      "#{t} AM"
    when 12
      "12 PM"
    when 13..23
      "#{t - 12} PM"
    end
  end

  HOURS_OF_DAY =
  {"12 AM" => 0,
    "1 AM" => 1,
    "2 AM" => 2,
    "3 AM" => 3,
    "4 AM" => 4,
    "5 AM" => 5,
    "6 AM" => 6,
    "7 AM" => 7,
    "8 AM" => 8,
    "9 AM" => 9,
    "10 AM" => 10,
    "11 AM" => 11,
    "12 PM" => 12,
    "1 PM" => 13,
    "2 PM" => 14,
    "3 PM" => 15,
    "4 PM" => 16,
    "5 PM" => 17,
    "6 PM" => 18,
    "7 PM" => 19,
    "8 PM" => 20,
    "9 PM" => 21,
    "10 PM" => 22,
    "11 PM" => 23
  }

end

app/controllers/availability_ranges_controller.rb
class AvailabilityRangesController < ApplicationController

  def new
    @availability_range = AvailabilityRange.new
  end

  def create
    @availability_range = AvailabilityRange.new(
      weekday: availability_range_params[:weekday],
      start_time: availability_range_params[:start_time],
      end_time: availability_range_params[:end_time],
      teacher_id: current_user.teacher.id
    )

    if @availability_range.save
      redirect_to user_path(current_user.id)
    else
      render 'new'
    end
  end

  def show
    @availability_ranges = AvailabilityRange.all
  end

  def edit
    @availability_range = AvailabilityRange.find(params[:id])
  end

  def update
    @availability_range = AvailabilityRange.find(params[:id])
    if @availability_range.update_attributes(availability_range_params)
      redirect_to user_url(current_user.id)
    else
      render 'edit'
    end
  end

  def destroy
    @availability_range = AvailabilityRange.find(params[:id])
    @availability_range.delete
    redirect_to user_url(current_user.id)
  end

  private
  def availability_range_params
    params.require(:availability_range).permit(:weekday, :start_time, :end_time)
  end
end

app/helpers/availability_ranges_helper.rb
module AvailabilityRangesHelper
end

app/views/availability_ranges/_edit.html.erb
<%= form_for @availability_range do |f| %>
  <h5 class="center">Change Availabilty for <%= @availability_range.weekday_name %></h5>
  <%= f.label :start_time %>
  <%= f.select(:start_time, AvailabilityRange::HOURS_OF_DAY) %>
  <br>
  <%= f.label :end_time %>
  <%= f.select(:end_time, AvailabilityRange::HOURS_OF_DAY) %>
  <span class="actions">
  <%= f.submit "Submit New Available Hours", class: "btn waves-effect waves-light"%>
  </span>
<% end %>

app/views/availability_ranges/_show.html.erb
  <div class="row center">
    <div class="col s2 offset-s1"><b>Day</b></div>
    <div class="col s2"><b>Start Time</b></div>
    <div class="col s2"><b>End Time</b></div>
    <div class="col s4"></div>
  </div>

<% (0..6).to_a.each do |d| %>
  <div class="row center">
    <% if @teacher.availability_ranges.find_by(weekday: d) %>
    <% t = @teacher.availability_ranges.find_by(weekday: d) %>
      <div class="col s2 offset-s1"><%= "#{t.weekday_name}" %></div>
      <div class="col s2"><%= "#{t.start_time_to_12h}" %></div>
      <div class="col s2"><%= "#{t.end_time_to_12h}" %></div>
        <% if current_user && current_user.id == @teacher.user_id %>
          <div class="col s12 m4"><button class="btn grey lighten-2 waves-teal waves-effect waves-light"><%= link_to "Edit", edit_availability_range_path(t.id) %></button>
            <button class="btn grey lighten-2 waves-teal waves-effect waves-light "><%= link_to "Delete", availability_range_path(t.id), method: :delete, data: {confirm: "Are you sure you want to delete?"}%></button>
          </div>
        <% end %>
    <% else %>
      <% if current_user && current_user.id == @teacher.user_id %>
      <% @availability_range = AvailabilityRange.new %>
      <%= form_for @availability_range do |f| %>
        <div class="col s2 offset-s1"><%= "#{Date::DAYNAMES[d]}" %> <%= f.hidden_field(:weekday, value: d)%></div>
        <div class="col s2"><%= f.select(:start_time, AvailabilityRange::HOURS_OF_DAY) %></div>
        <div class="col s2"><%= f.select(:end_time, AvailabilityRange::HOURS_OF_DAY) %></div>
        <div class="col m4 s12"><span class="actions"><%= f.submit "Add #{Date::DAYNAMES[d]} ", class: "btn grey lighten-2 waves-teal waves-effect waves-light light-blue-text"%></span></div>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/availability_ranges/_update.html.erb
<!-- Find all the days that a teacher has a current availability range record and add each of those days to the days_used array -->
<% days_used = [] %>
<% @teacher.availability_ranges.each { |r| days_used << r.weekday } %>

<!-- For each day that they have no availabilty range, render a form to add hours -->
<% days = Array (0..6) %>
<% days.each do |d| %>
  <% unless days_used.include?(d) %>
    <% @availability_range = AvailabilityRange.new %>
    <%= form_for @availability_range do |f| %>
      <%= f.hidden_field(:weekday, value: d)%>
      <%= f.label :start_time %>
      <%= f.select(:start_time, AvailabilityRange::HOURS_OF_DAY) %>
      <%= f.label :end_time %>
      <%= f.select(:end_time, AvailabilityRange::HOURS_OF_DAY) %>
      <span class="actions"><%= f.submit "Add #{Date::DAYNAMES[d]} ", class: "btn waves-effect waves-light" %></span>
    <% end %>
  <% end %>
<% end %>

app/views/availability_ranges/edit.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col m4 offset-m4 s12 center">

<%= render 'edit' %>

    </div>
  </div>
  <br>
  <br>
  <br>
</div>

app/views/availability_ranges/new.html.erb
<% if @availability_range.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@availability_range.errors.count, "Error") %> prevented this from being created:</h2>

       <ul>
         <% @availability_range.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

<h1>AvailabilityRanges</h1>
<% weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] %>
<% x = 0 %>
<% 7.times do %>
  <%= form_for @availability_range  do |f| %>
    <label for="weekday"></label>
    <%= f.hidden_field(:weekday, value: x)%>
    <%= f.label :start_time %>
    <%= f.select(:start_time, AvailabilityRange::HOURS_OF_DAY) %>
    <%= f.label :end_time %>
    <%= f.select(:end_time, AvailabilityRange::HOURS_OF_DAY) %>
    <span class="actions">
    <%= f.submit "Add #{weekdays[x]} hours", class: "btn waves-effect waves-light" %>
    </span>
    <% x = x + 1 %>
  <% end %>
<% end %>

app/views/availability_ranges/show.html.erb
<h3>Availability</h3>
<table>
  <th>
    <tr>Day</tr>
    <tr>Start Time</tr>
    <tr>End Time</tr>
  </th>
  <% @teacher.availability_ranges.each do |r| %>
  <tr>
    <td><%= "#{r.weekday_name}" %></td>
    <td><%= "#{r.start_time_to_12h}" %></td>
    <td><%= "#{r.end_time_to_12h}" %></td>
  </tr>
  <% end %>
</table>