config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/teachers')

  resources :subjects, only: [:index, :show]

  resources :students, only: [:new, :create, :edit, :update]

  resources :teachers, only: [:new, :create, :edit, :update, :index, :show] do
    resources :lessons, only: [:new, :create]
  end

  resources :lessons, only: [:show, :destroy]

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :availability_ranges, only: [:new, :create, :show, :edit, :update, :destroy]



end

app/models/user.rb
class User < ApplicationRecord
  has_one :student
  has_one :teacher
  has_secure_password
  before_save :lowercase_email

  validates :first_name, :last_name, :password_confirmation, presence: true
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  def lowercase_email
    self.email = self.email.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    if current_user
      if current_user.teacher
        @teacher = Teacher.find_by(user_id: current_user.id)
        @availability_ranges = @teacher.availability_ranges.sort { |a,b| a.weekday <=> b.weekday }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_loginmessage.html.erb
<h3>Please log in!</h3>

app/views/users/new.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col m4 offset-m4 s12 center">
      <h5>Sign up for Étude</h5>
        <%= form_for @user do |f| %>
          <% if @user.errors.any? %>
            <h2><%= pluralize(@user.errors.count, "error") %></h2>
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            <% end %>
              </ul>
          <div class="field">
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name %>
          </div>
          <div class="field">
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name %>
          </div>
          <div class="field">
            <%= f.label :email %><br />
            <%= f.text_field :email %>
          </div>
          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password %>
          </div>
          <div class="field">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation %>
          </div>
          <div class="actions btn waves-effect waves-light"><%= f.submit %></div>
        <% end %>
      <br>
      <br>
      <br>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container center">
<% if current_user == nil %>
  <%= render 'loginmessage' %>
<% else %>

<!-- Student Section Starts Here -->
  <% if current_user.student %>

    <!-- Showing Students Lessons if they have any -->
    <% if current_user.student.lessons.length > 0 %>
    <!-- Showing lessons that are in the future -->
    <h5>Upcoming lessons</h5>
    <div id="current-student-lessons">
          <table class="striped responsive-table">
            <thead>
              <tr>
                <th>Teacher</th>
                <th>Time</th>
                <th>Format</th>
                <th></th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
          <% current_user.student.lessons.each do |l| %>
          <% if l.time > Time.now %>
            <tr>
                  <td><%= "#{l.teacher.first_name} #{l.teacher.last_name}" %></td>
                  <td><%= "#{l.time.strftime("%A, %B %d, %Y at %I:%M %p")}" %></td>
                  <% if l.format == 'offline' %>
                    <td><i class="small material-icons">location_on</i></td>
                    <td>In Person</td>
                  <% else %>
                    <td><i class="small material-icons">desktop_mac</i></td>
                    <td>Online</td>
                  <% end %>
                  <td><%= link_to "View Lesson", lesson_path(l.id) %></td>
            </tr>
            <% end %>
          <% end %>
            </tbody>
          </table>
        </div>
      <!-- Showing Lessons that are in the past -->
      <% if current_user.student.lessons.where(time: Time.now-5.years..Time.now).count > 0 %>
      <h5>Past lessons</h5>
      <div id="past-student-lessons">
            <table class="striped responsive-table">
              <thead>
                <tr>
                  <th>Teacher</th>
                  <th>Time</th>
                  <th>Format</th>
                </tr>
              </thead>
              <tbody>
            <% current_user.student.lessons.each do |l| %>
            <% if l.time < Time.now %>
              <tr>
                    <td><%= "#{l.teacher.first_name} #{l.teacher.last_name}" %></td>
                    <td><%= "#{l.time.strftime("%A, %B %d, %Y at %I:%M %p")}" %></td>
                    <td><%= l.format.titleize %></td>
              </tr>
              <% end %>
            <% end %>
          <% end %>
              </tbody>
            </table>
          </div>
    <!-- Showing that a student hasn't booked any lessons -->
    <% else %>
    <h3>You have not booked any lessons!</h3>
    <% end %>
  </section>
<!-- Teacher section starts here -->
  <% elsif current_user.teacher %>
  <div class=row>
    <div class="fixed-action-btn toolbar">
      <a class="btn-floating btn-large teal">
        <i class="large material-icons">mode_edit</i>
      </a>
      <ul>
        <li class="waves-effect waves-light"><a href=<%= edit_teacher_path %>><i class="material-icons"></i>Edit Profile</a></li>
        <li class="waves-effect waves-light"><a href="#upcoming"><i class="material-icons"></i>Upcoming Lessons</a></li>
        <li class="waves-effect waves-light"><a href="#past"><i class="material-icons"></i>Past Lessons</a></li>
        <li class="waves-effect waves-light"><a href="#availability"><i class="material-icons"></i>Edit Availability</a></li>
      </ul>
    </div>
  </div>

    <% if @teacher.lessons.length != 0  %>
    <a name="upcoming"></a>
    <h5>Upcoming lessons</h5>
    <div id="current-teacher-lessons">
        <table class="striped responsive-table">
          <thead>
            <tr>
              <th>Student</th>
              <th>Time</th>
              <th></th>
              <th>Format</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
        <% current_user.teacher.lessons.each do |l| %>
        <% if l.time > Time.now %>
          <tr>
                <td><%= "#{l.student.first_name} #{l.student.last_name}" %></td>
                <td><%= "#{l.time.strftime("%A, %B %d, %Y at %I:%M %p")}" %></td>
                <% if l.format == 'offline' %>
                  <td><i class="small material-icons">location_on</i></td>
                  <td>In Person</td>
                <% else %>
                  <td><i class="small material-icons">desktop_mac</i></td>
                  <td>Online</td>
                <% end %>
                <td><%= link_to "View Lesson", lesson_path(l.id) %></td>
          </tr>
          <% end %>
        <% end %>
          </tbody>
        </table>
      </div>
      <% if current_user.teacher.lessons.where(time: Time.now-5.years..Time.now).count > 0 %>
        <a name="past"></a>
        <h5>Past Lessons</h5>
        <div id="past-teacher-lessons">
            <table class="striped responsive-table">
              <thead>
                <tr>
                  <th>Student</th>
                  <th>Time</th>
                  <th>Format</th>
                </tr>
              </thead>
              <tbody>
            <% current_user.teacher.lessons.each do |l| %>
              <% if l.time < Time.now %>
              <tr>
                    <td><%= "#{l.student.first_name} #{l.student.last_name}" %></td>
                    <td><%= "#{l.time.strftime("%A, %B %d, %Y at %I:%M %p")}" %></td>
                    <td><%= l.format.titleize %></td>
              </tr>
              <% end %>
            <% end %>
          <% end %>
            </tbody>
          </table>
        </div>
        <br>
        <div class="divider"></div>
        <br>
        <a name="availability"></a>
      <div class="row center">
        <h5><%= "You are available for lessons #{@teacher.availability_ranges.count} days a week" %></h5>
        <br>
        <br>
        <%= render 'availability_ranges/show' %>
      </div>
        <br>
        <br>
    <% else %>
    <h5>No one has booked a lesson with you yet</h5>
    <% end %>

    <% else %>
    <h5>Please select whether you'd like to learn or teach!</h5>
  <% end %>
<% end %>
</div>