config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/teachers')

  resources :subjects, only: [:index, :show]

  resources :students, only: [:new, :create, :edit, :update]

  resources :teachers, only: [:new, :create, :edit, :update, :index, :show] do
    resources :lessons, only: [:new, :create]
  end

  resources :lessons, only: [:show, :destroy]

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :availability_ranges, only: [:new, :create, :show, :edit, :update, :destroy]



end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :lessons
  has_many :availability_ranges
  has_many :students, through: :lessons

  validates :subject, :postal_code, :bio, :picture, :teaching_since, :street_address, :city, :province, presence: true
  validates :price, numericality: {only_integer: true}
  validate :teaching_since_valid

  def first_name
    User.find(self.user_id).first_name
  end

  def last_name
    User.find(self.user_id).last_name
  end

  def email
    User.find(self.user_id).email
  end

  def availability_ok?(date)
    weekday = date.wday
    hour = date.hour
    self.availability_ranges.each do |a|
      if a.weekday == weekday && a.start_time <= hour && a.end_time > hour
        return true
      end
    end
    return false
  end

  def available?(time)
    if lessons.length > 0
      lessons.each do |l|
        if l.time == time
          return false
        end
      end
    end
    return true
  end

  def teaching_since_valid
    if self.teaching_since != nil
      unless Time.now > self.teaching_since
        errors.add(:time, 'Your "teaching since" entry must be in the past')
      end
    end
  end

  def full_address
    "#{self.street_address},#{self.postal_code}".gsub!(" ", "+")
  end
end

SUBJECTS = ['Spanish', 'Guitar', 'French', 'Drums', 'Recorder', 'Samba', 'Welding',
  'Woodworking', 'Scrapbooking', 'Knitting', 'Korean', 'Cooking', 'Karate', 'Bridge',
  'Fishing', 'Waterskiing', 'Kiteboarding', 'Trombone', 'Trumpet', 'Boxing']

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @eric = User.find_by(last_name: "Hartman").teacher
    @teachers = Teacher.all
    @teachersfeat = Teacher.order(teaching_since: :asc).take(4)
    @teachersnew = Teacher.order(teaching_since: :desc).take(4)
    @subjects = @teachers.select("subject").group("subject")
  end

  def new
    @teacher = Teacher.new
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def create
    @user = current_user
    @teacher = Teacher.new(
      price: teacher_params[:price],
      subject: teacher_params[:subject],
      postal_code: teacher_params[:postal_code],
      bio: teacher_params[:bio],
      picture: teacher_params[:picture],
      teaching_since: teacher_params[:teaching_since],
      street_address: teacher_params[:street_address],
      city: teacher_params[:city],
      province: teacher_params[:province],
      'user_id' => @user.id
    )

    if @teacher.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @teacher = Teacher.find_by(user_id: params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    if @teacher.update_attributes(teacher_params)
      redirect_to user_path
    else
      render edit_teacher_path
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:price, :subject, :postal_code, :bio, :picture, :teaching_since, :street_address, :city, :province)
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col m4 offset-m4 s12 center">

      <%= form_for @teacher do |f| %>
        <% if @teacher.errors.any? %>
          <h2><%= pluralize(@teacher.errors.count, "error") %></h2>
            <ul>
              <% @teacher.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
          <% end %>
            </ul>
        <div class="field">
          <%= f.label :bio %><br />
          <%= f.text_area :bio, :rows => "5" %>
        </div>
        <div class="field">
          <%= f.label :picture %><br />
          <%= f.text_field :picture %>
        </div>
        <div class="field">
          <%= f.label :subject %><br />
          <%= f.select(:subject, Teacher::SUBJECTS) %>
        </div>
        <div class="field">
          <%= f.label :lesson_price_per_hour %><br />
          <%= f.number_field(:price, in: 1..10000) %>
        </div>
        <div class="field">
          <%= f.label :street_address %><br />
          <%= f.text_field :street_address %>
        </div>
        <div class="field">
          <%= f.label :city %><br />
          <%= f.text_field :city %>
        </div>
        <div class="field">
          <%= f.label :province %><br />
          <%= f.text_field :province  %>
        </div>
        <div class="field">
          <%= f.label :teaching_since %><br />
          <%= f.text_field :teaching_since, class: "datepicker" %>
        </div>

        <div class="field">
          <%= f.label :postal_code %><br />
          <%= f.text_field :postal_code %>
        </div>
        <div class="actions btn waves-effect waves-light"><%= f.submit 'Update' %></div>
      <% end %>

    </div>
  </div>
  <br>
  <br>
  <br>
</div>

app/views/teachers/edit.html.erb
<div class="center">
  <h2>Edit your profile</h2>
</div>
<%= render "form" %>

app/views/teachers/index.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center white-text text-lighten-5">Welcome to Étude</h1>
      <div class="row center">
        <h5 class="header col s12 white-text light">Where Freelance Teachers and Students Connect</h5>
      </div>
      <% if current_user && current_user.student == nil && current_user.teacher == nil %>
        <div class="row center">
          <a href="<%= new_teacher_path %>" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Teaching</a><br /><br />
          <a href="<%= new_student_path %>" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Learning</a>
        </div>
      <% end %>
      <% if current_user == nil %>
        <div class="row center">
          <a href="<%= new_user_path %>" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a><br /><br />
        </div>
      <% end %>
      <br><br>

    </div>
  </div>
  <div class="parallax"><img src="/hands.jpg" alt="Unsplashed background img 1"></div>
</div>


<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m6">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="medium material-icons">face</i><i class="medium material-icons">school</i></h2>
          <h5 class="center">For Teachers</h5>

          <p class="light">Are you the master of a subject and want to connect with students who are ready to learn?
            Étude provides a platform for freelance teachers to build a profile, share their experience, and book
            both online and in person lessons with students who are eager to learn. <br /><br /> Fill out your profile and start
            booking lessons today!
          </p>
        </div>
      </div>

      <div class="col s12 m6">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="medium material-icons">group</i><i class="medium material-icons">local_library</i></h2>
          <h5 class="center">For Students</h5>

          <p class="light"><%= "Keen to learn #{@eric.subject} from Eric?  I wouldn't be, but whatever, the guy for some reason thinks he is
            good enough at #{@eric.subject} to warrant taking your money in exchange for spending time with him.  Worth it? We
            will leave that to you to find out. "%> <br /><br />Book a lesson with Eric at your own risk, or maybe check out some of our other teachers instead...</p>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">

  </div>
  <div class="parallax"><img src="pianolessons.jpg" alt="Unsplashed background img 2"></div>
</div>

<div class="container">
  <div class="section">
    <div class="row">
      <div class="col s12 center">
        <h3><i class="mdi-content-send brown-text"></i>Find Teachers by Subject</h3>
        <ul>
        <% @subjects.each do |s| %>
          <div class="chip hoverable">
            <%= link_to s.subject, subjects_url(:subject => s.subject) %>
          </div>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="divider"></div>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col s12 m6">
      <h4>Featured Teachers</h4>
      <ul class="collection">
        <% @teachersfeat.each do |t| %>
        <a href="<%= teacher_path(t) %>">
        <li class="collection-item avatar teal lighten-4" href="#">
          <img src="<%= t.picture %>" alt="<%= t.first_name %> Picture" class="circle">
          <span class="title"><%= "#{t.first_name} #{t.last_name}" %></span>
          <p class="teacher-subject"><%=  "#{t.subject} " %></p>
          <p class="teacher-price"><%=  "$ #{t.price} " %></p>
          <a href="#!" class="secondary-content orange-text">
          <% rand(4..5).times do %>
          <i class="material-icons">grade</i>
          <% end %>
          </a></a>
        </li>
        <% end %>
      </ul>
    </div>
      <div class="col s12 m6">
        <h4>Newest Teachers</h4>
        <ul class="collection">
          <% @teachersnew.each do |t| %>
          <a href="<%= teacher_path(t) %>">
          <li class="collection-item avatar brown lighten-4">
            <img src="<%= t.picture %>" alt="<%= t.first_name %> Picture" class="circle">
            <span class="title"><%= "#{t.first_name} #{t.last_name}" %></span>
            <p class="teacher-subject"><%=  "#{t.subject} " %></p>
            <p class="teacher-price"><%=  "$ #{t.price} " %></p>
            <a href="#!" class="secondary-content orange-text">
            <% rand(1..4).times do %>
            <i class="material-icons">grade</i>
            <% end %>
            </a></a>
          </li>
          <% end %>
        </ul>
      </div>
  </div>
</div>

app/views/teachers/new.html.erb
<div class="center">
<h1>Sign Up To Teach</h1>
</div>
<%= render "form" %>

app/views/teachers/show.html.erb
<div class="container">
<!-- Row 1 -->
  <div class="row">
    <div class="col s12 m6">
      <!-- Teacher image -->
      <h5><img id="teacher-img" src="<%= @teacher.picture %>" alt="<%= @teacher.first_name %> Picture"></h5>
    </div>
    <div class="col s12 m6">
      <!-- Book Lesson link -->
      <h6><%= link_to 'Book Lesson', new_teacher_lesson_path(@teacher.id) %></h6>
      <!-- Full name -->
      <h5><%= "#{@teacher.first_name} #{@teacher.last_name}" %></h5>
      <!-- Subject -->
      <h5><%= "Subject: #{@teacher.subject}" %></h5>
      <!-- Teaching Since -->
      <h5><%= "Teaching since: #{@teacher.teaching_since}" %></h5>
    </div>
  </div>
<!-- Row 2 -->
  <div class="row">
    <div class="col s12">
      <!-- About -->
      <h5> <%= "About #{@teacher.first_name}" %></h5>
      <p><%= "#{@teacher.bio}" %></p>
    </div>
  </div>
<!-- Row 3 -->
  <div class="row">
    <div class="col s12 m6 center">
      <!-- Street Address -->
      <h5> <%= "#{@teacher.first_name}'s address" %></h3>
      <h5><%= "#{@teacher.street_address}, #{@teacher.city}" %></h5>
      <h5><%= "#{@teacher.province}, #{@teacher.postal_code}" %></h5>
      <br>
      <div class="divider"></div>

      <br>
      <!-- Availability -->
      <h5 class="center"> <%= "#{@teacher.first_name}'s availability" %></h3>
        <br>
      <% @teacher.availability_ranges.each do |a| %>
        <%= "#{a.weekday_name[0, 3]} #{a.start_time_to_12h} - #{a.end_time_to_12h}" %><br>
      <% end %>
      <br>
      <br>
      <div class="divider"></div>

      <!-- Cost -->
      <h5><%= "Cost per lesson: $#{@teacher.price}" %></h5>
      <!-- Book lesson -->
      <h5><%= link_to 'Book Lesson', new_teacher_lesson_path(@teacher.id) %></h5>
    </div>
    <div class="col s12 m6">
      <br>
      <br>
      <iframe
      width="100%"
      height="500px"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=<%= Rails.application.secrets.maps_key %>&q=<%= @teacher.full_address %>" allowfullscreen>
    </iframe>
    </div>
    <br>
  </div>
<!-- Row 4 -->

</div>