config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/teachers')

  resources :subjects, only: [:index, :show]

  resources :students, only: [:new, :create, :edit, :update]

  resources :teachers, only: [:new, :create, :edit, :update, :index, :show] do
    resources :lessons, only: [:new, :create]
  end

  resources :lessons, only: [:show, :destroy]

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :availability_ranges, only: [:new, :create, :show, :edit, :update, :destroy]



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Etude</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">

  </head>

  <body class="grey lighten-5">
    <nav class="black" role="navigation">
      <div class="nav-wrapper container">
        <a id="logo-container" href="<%= root_path %>" class="brand-logo">Étude</a>
        <ul class="right hide-on-med-and-down">
          <li><a href="<%= root_path %>"><i class="medium material-icons">home</i></a></li>
          <% unless current_user %>
            <li><%= link_to 'Sign Up', new_user_path %></li>
            <li><%= link_to 'Log In', new_session_path %></li>
          <% end %>
          <% if current_user %>
          <li><%= "Hello #{current_user.first_name}!" %></li>
          <li><a href="<%= user_path(current_user.id) %>"><%= "Profile" %></a></li>
          <li><%= link_to 'Log Out', session_path(current_user.id), :method => :delete %></li>
          <% end %>
        </ul>
        <ul id="nav-mobile" class="side-nav">
          <li><a href="<%= root_path %>">Main</a></li>
          <% unless current_user %>
            <li><%= link_to 'Sign Up', new_user_path %></li>
            <li><%= link_to 'Log In', new_session_path %></li>
          <% end %>
          <% if current_user %>
          <li><a href="<%= user_path(current_user.id) %>"><%= "Your Profile" %></a></li>
          <li><%= link_to 'Log Out', session_path(current_user.id), :method => :delete %></li>
          <% end %>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
    </nav>
      <%= yield %>

    <footer class="page-footer black">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">About Étude</h5>
        <p class="grey-text text-lighten-4">While currently revenue impaired, the intention is for Étude to evolve into a for-profit operation, on par with Goldman Sachs. As soon as we
        figure out how to actually make a profit, we'll be popping bottles like DJ Khaled alone in a pool somewhere. <br /><br />
        Until that happens, enjoy booking lessons through us for free!</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Legal</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">LinkedIn (for Aurora)</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 Étude
    </div>
  </div>
</footer>
  </body>
</html>